# Generated by Django 3.2.9 on 2021-11-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211125_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='mainapp.Category'),
        ),
    ]
